---

version: "3"

services:

        flask-app:

                build:

                        context: ./

                        dockerfile: ./Dockerfile

                ports:
                        - 5000:5000

                image: silvermadison/iss_tracker.py:1.0

                #volumes:
                #- ./config.yaml:/config.yaml

